repos:
  # Basic
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      -   id: trailing-whitespace
      -   id: end-of-file-fixer
      -   id: check-yaml
          exclude: ^\.onedev-buildspec\.yml$
      -   id: check-added-large-files
          args: ['--maxkb=3000']
      -   id: check-json
      -   id: check-toml
      -   id: detect-private-key
      -   id: mixed-line-ending

  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff
    rev: v0.9.4
    hooks:
      # Run the linter.
      - id: ruff
        args: [--fix]
      # Run the formatter.
      - id: ruff-format

  - repo: local
    hooks:
      # Pezin version control hook
      - id: pezin-commit-msg
        name: Pezin Version Control
        entry: python3 -m pezin.hooks.pre_commit
        language: system
        stages: [commit-msg]
        always_run: true
        pass_filenames: false
