"""Slow e2e: hooks generated by `pezin install-hooks` commit without the
installing venv on PATH.

Regression test for the `#!/usr/bin/env python3` shebang defect: pipx/uv/venv
installs put pezin only inside the venv, so an ambient python3 cannot import
it, and the failing prepare-commit-msg aborted every commit.
"""

import os
import subprocess
from pathlib import Path

import pytest

from tests.hooks.conftest import BIN_DIR, PY

pytestmark = pytest.mark.slow


def _path_without_venv() -> str:
    """PATH with the test venv's bin dir removed, keeping system dirs."""
    parts = [
        p for p in os.environ.get("PATH", "").split(os.pathsep) if p and p != BIN_DIR
    ]
    return os.pathsep.join(parts)


def test_install_hooks_commits_without_venv_on_path(tmp_path: Path) -> None:
    repo = tmp_path / "repo"
    repo.mkdir()
    env = os.environ.copy()
    env["PATH"] = _path_without_venv()
    env.pop("PYTHONPATH", None)  # pezin must resolve via the pinned shebang only

    def git(*args: str) -> subprocess.CompletedProcess:
        return subprocess.run(
            ["git", *args], cwd=repo, capture_output=True, text=True, env=env
        )

    assert git("init", "-q", "-b", "main").returncode == 0
    assert git("config", "user.email", "t@e.com").returncode == 0
    assert git("config", "user.name", "T").returncode == 0

    (repo / "pyproject.toml").write_text(
        '[project]\nname = "demo"\nversion = "0.1.0"\n\n'
        '[tool.pezin]\nversion_files = [{path = "pyproject.toml"}]\n'
    )
    assert git("add", "-A").returncode == 0
    assert git("commit", "-q", "-m", "chore: seed", "--no-verify").returncode == 0

    # Install hooks with the venv python; the venv is NOT on PATH afterwards.
    install = subprocess.run(
        [PY, "-m", "pezin", "install-hooks"],
        cwd=repo,
        capture_output=True,
        text=True,
        env=env,
        timeout=120,
    )
    assert install.returncode == 0, install.stderr

    hook = repo / ".git" / "hooks" / "prepare-commit-msg"
    assert hook.exists()
    assert hook.read_text().splitlines()[0] == f"#!{PY}"

    (repo / "feature.txt").write_text("new\n")
    assert git("add", "-A").returncode == 0
    commit = git("commit", "-q", "-m", "feat: add feature file")
    assert commit.returncode == 0, commit.stderr
    assert "Could not find pezin package" not in commit.stderr

    # Version bumped and amended into the commit.
    assert 'version = "0.2.0"' in (repo / "pyproject.toml").read_text()
    tags = git("tag", "--list").stdout.split()
    assert tags == ["v0.2.0"]

    # Changelog written in Keep-a-Changelog order.
    changelog = (repo / "CHANGELOG.md").read_text()
    assert changelog.index("## [Unreleased]") < changelog.index("## [0.2.0]")
    assert "- add feature file" in changelog

    stat = git("show", "--stat", "--oneline", "HEAD").stdout
    assert "CHANGELOG.md" in stat
    assert "pyproject.toml" in stat
